### ISSUE TITLE
File searches fail for text which isn't lower-case in a MySQL/MariaDB database

### ISSUE THREAD

**Issue by RoystonS** [bacularis/bacularis-api#1]
Hi there,
I'm trying to search for files using the bacularis 'search for files in job' feature, but unfortunately the search doesn't find files that have mixed case paths.

For example, if I have a path of '/home/user/Foo Bar', a search for 'oo' will find the file, a search for 'ar' will find the file, but searches for either 'foo' or 'Foo' fail to find it.

What seems to be happening is that with MySQL/MariaDB, the Path column is stored as a BLOB, and the LOWER function doesn't work on BLOBs.  So Bacularis is lower-casing the search text, attempting (but failing) to lower-case the Path text, and comparing the two, and so the search doesn't match if the Path text is mixed-case.

The problem is this lower-case conversion here:
https://github.com/bacularis/bacularis-api/blob/master/API/Modules/JobManager.php#L351

The MariaDB and MySQL documentation says:

> 
> LOWER() (and [UPPER](https://mariadb.com/kb/en/upper/)()) are ineffective when applied to binary strings ([BINARY](https://mariadb.com/kb/en/binary/), [VARBINARY](https://mariadb.com/kb/en/varbinary/), [BLOB](https://mariadb.com/kb/en/blob/)). To perform lettercase conversion, [CONVERT](https://mariadb.com/kb/en/convert/) the string to a non-binary string
> 
> LOWER(CONVERT(@str USING latin1));
> 

Changing the Bacularis `JobManager.php` line to

```
         $search_crit = " AND (LOWER(CONVERT(Path.Path USING utf8)) LIKE LOWER('%$search%') OR LOWER(CONVERT(File.Filename USING utf8)) LIKE LOWER('%$search%')) ";
```
fixes the problem.

(But using `CAST` might be better than `CONVERT` because both Postgres and Sqlite also support that syntax, it seems...)

**Comment by ganiuszka** [comment]
Hello Royston,

Thank you for detailed bug report and for describing proposed solutions. Yes, you are fully right that the conversion for BLOB is needed.

Basing on your research I prepared a patch that uses CONVERT() function for the MySQL/MariaDB catalog type. Your idea with using CAST() in my opinion is good as well and it would be used if the problem would exist for other supported database types.

Thank you again.

**Comment by RoystonS** [comment]
Nice one - thank you!
