### ISSUE TITLE
Is openapi_bacularis.json valid and up to date?

### ISSUE THREAD

**Issue by daramousk** [bacularis/bacularis-api#5]
Hi,

I am trying to parse the openapi spec to generate some client libraries on https://editor.swagger.io/ but it seems there are some issues, has it been updated to version 3.0.0? Is this spec valid?

Pasting some of the errors below:

```
Structural error at 
should NOT have additional properties
additionalProperty: server, definitions
Jump to line 0
Structural error at paths./api/v2/clients/{clientid}/bandwidth.put.parameters.1
should NOT have additional properties
additionalProperty: default
Jump to line 581
Structural error at paths./api/v2/clients/{clientid}/bandwidth.put.parameters.1.in
should be equal to one of the allowed values
allowedValues: path, query, header, cookie
Jump to line 582
Structural error at paths./api/v2/jobs/{jobid}/cancel.put
should NOT have additional properties
additionalProperty: consumes
Jump to line 783
Structural error at paths./api/v2/jobs/{jobid}/bandwidth.put.parameters.1
should NOT have additional properties
additionalProperty: default
Jump to line 901
Structural error at paths./api/v2/jobs/{jobid}/bandwidth.put.parameters.1.in
should be equal to one of the allowed values
allowedValues: path, query, header, cookie
Jump to line 902
```

**Comment by ganiuszka** [comment]
Hello @daramousk,

Thank you for your report.

I checked it in the indicated online editor and I received the same results as yours. It looks that the API spec in some parts is not valid with OpenAPI 3.0. It needs to be fixed.

In the Bacularis API documentation we use a bit old Swagger UI that is not too sensitive on these errors. You can use it here until time we correct the OpenAPI structure:

https://bacularis.app/api/

Thanks for showing us this problem. We will inform here when it is fixed.

Best regards,
Marcin Haba (gani)

**Comment by ganiuszka** [comment]
Hello @daramousk

I am writing to let you know that I fixed the incorrect API specification. Now it should be valid with OpenAPI 3.0.

Thanks again.

Best regards,
Marcin Haba (gani)
